version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
